# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Your awesome title
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-relative-links
  - jekyll-timeago
  - jekyll-compose

relative_links:
  enabled:     true
  collections: true


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

home_page_products:
  - name: "Natural Wholes Raw Cashew Nuts W320"
    image: "320-cashew-nuts-kernels.jpg"
    description: "Premium quality cashew nuts - W320"
    link: ""
    pacakage_size: "10 Kg"
    packing_type: "Carton, Tin"
    color: "White"
    life: "6 Months"
    processing_type: "Raw, Roasted"

  - name: "W180 Jumbo Cashew Nuts"
    image: "180-cashew-nuts-kernels.jpg"
    description: "W-180, is the King of Cashew - They are larger in size."
    link: ""
    pacakage_size: "10 Kg"
    packing_type: "Carton, Tin"
    color: "White"
    life: "6 Months"
    processing_type: "Raw, Roasted"

  - name: "JH Cashew Nuts"
    image: "jh-cashew-nuts-kernels.jpg"
    description: "W-180, is the King of Cashew - They are larger in size."
    link: ""
    pacakage_size: "10 Kg"
    packing_type: "Carton, Tin"
    color: "White"
    life: "6 Months"
    processing_type: "Raw, Roasted"


products:
  - name: "Natural Wholes Raw Cashew Nuts W320"
    image: "320-cashew-nuts-kernels.jpg"
    description: "Premium quality cashew nuts - W320"
    link: ""
    pacakage_size: "10 Kg"
    packing_type: "Carton, Tin"
    color: "White"
    life: "6 Months"
    processing_type: "Raw, Roasted"

  - name: "W180 Jumbo Cashew Nuts"
    image: "180-cashew-nuts-kernels.jpg"
    description: "W-180, is the King of Cashew - They are larger in size."
    link: ""
    pacakage_size: "10 Kg"
    packing_type: "Carton, Tin"
    color: "White"
    life: "6 Months"
    processing_type: "Raw, Roasted"

  - name: "JH Cashew Nuts"
    image: "jh-cashew-nuts-kernels.jpg"
    description: "W-180, is the King of Cashew - They are larger in size."
    link: ""
    pacakage_size: "10 Kg"
    packing_type: "Carton, Tin"
    color: "White"
    life: "6 Months"
    processing_type: "Raw, Roasted"

  - name: "210 Cashew Nuts"
    image: "210-cashew-nuts-kernels.jpg"
    description: "W-180, is the King of Cashew - They are larger in size."
    link: ""
    pacakage_size: "10 Kg"
    packing_type: "Carton, Tin"
    color: "White"
    life: "6 Months"
    processing_type: "Raw, Roasted"

  - name: "SJH Spilts Cashew Nuts"
    image: "sjh-cashew-nuts.jpg"
    description: "W-180, is the King of Cashew - They are larger in size."
    link: ""
    pacakage_size: "10 Kg"
    packing_type: "Carton, Tin"
    color: "White"
    life: "6 Months"
    processing_type: "Raw, Roasted"

  - name: "SS Spilts Cashew Nuts"
    image: "ss-cashew-nuts.jpg"
    description: "W-180, is the King of Cashew - They are larger in size."
    link: ""
    pacakage_size: "10 Kg"
    packing_type: "Carton, Tin"
    color: "White"
    life: "6 Months"
    processing_type: "Raw, Roasted"

  - name: "JK Spilts Cashew Nuts"
    image: "jk-cashew-nuts.jpg"
    description: "W-180, is the King of Cashew - They are larger in size."
    link: ""
    pacakage_size: "10 Kg"
    packing_type: "Carton, Tin"
    color: "White"
    life: "6 Months"
    processing_type: "Raw, Roasted"

  - name: "K Spilts Cashew Nuts"
    image: "k-cashew-nuts.jpg"
    description: "W-180, is the King of Cashew - They are larger in size."
    link: ""
    pacakage_size: "10 Kg"
    packing_type: "Carton, Tin"
    color: "White"
    life: "6 Months"
    processing_type: "Raw, Roasted"

  - name: "SWPI Spilts Cashew Nuts"
    image: "swpi-cashew-nuts.jpg"
    description: "W-180, is the King of Cashew - They are larger in size."
    link: ""
    pacakage_size: "10 Kg"
    packing_type: "Carton, Tin"
    color: "White"
    life: "6 Months"
    processing_type: "Raw, Roasted"

  - name: "LWP Spilts Cashew Nuts"
    image: "lwp-cashew-nuts.jpg"
    description: "W-180, is the King of Cashew - They are larger in size."
    link: ""
    pacakage_size: "10 Kg"
    packing_type: "Carton, Tin"
    color: "White"
    life: "6 Months"
    processing_type: "Raw, Roasted"

  - name: "DP Spilts Cashew Nuts"
    image: "dp-cashew-nuts.jpg"
    description: "W-180, is the King of Cashew - They are larger in size."
    link: ""
    pacakage_size: "10 Kg"
    packing_type: "Carton, Tin"
    color: "White"
    life: "6 Months"
    processing_type: "Raw, Roasted"

  - name: "JB Cashew Nuts"
    image: "jb-cashew-nuts.jpg"
    description: "W-180, is the King of Cashew - They are larger in size."
    link: ""
    pacakage_size: "10 Kg"
    packing_type: "Carton, Tin"
    color: "White"
    life: "6 Months"
    processing_type: "Raw, Roasted"





